// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.gradleToolsVersion = '9.3.1'

    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:${gradleToolsVersion}"
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
    }
}

ext {
    apkNamePrefix = 'DataStats'
    versionName = "4.0.1"
    versionCode = 37

    compileSdkVersion = 37
    buildToolsVersion = '37.0.0'

    targetSdkVersion = 36
    minSdkVersion = 23
}